### ISSUE TITLE
How will the cards be ordered? By most recently edited?

### ISSUE THREAD

**Issue by kirstylaurence** [guyirvine/haveyoursay#10]

**Comment by guyirvine** [comment]
Not sure, to be honest.

If we want to try and push cards through, should we put least recently edited at the top ? eg, Make it obvious that "this one's been hanging around for while".

**Comment by kirstylaurence** [comment]
Yes Guy I agree. The Oldest card at the top

**Comment by guyirvine** [comment]
Done.
