### ISSUE TITLE
How do people add dots for support? by clicking on a dot?

### ISSUE THREAD

**Issue by kirstylaurence** [guyirvine/haveyoursay#11]

**Comment by guyirvine** [comment]
Put a budget version of Facebook likes on the "Board Cards".

Might be cooler to have a read-only version on the "Board Card", then a clickable version once you open the card.

Need to store the fact you've liked it in the browser, so we can 'unlike' it.

**Comment by kirstylaurence** [comment]
Is it better to have like face book with a 'Like' button and then the number of total likes to the right. Not obvious that you click the '12 likes' to add your own like.

**Comment by guyirvine** [comment]
I think we're happy here.
