### ISSUE TITLE
Once someone has written a question and the why, do we wan these bits to be editable? Others may choose to change the wording slightly unlike with the board you can't edit what's already written

### ISSUE THREAD

**Issue by kirstylaurence** [guyirvine/haveyoursay#15]

**Comment by guyirvine** [comment]
If they mis-type something, do we want to give them opportunity to correct it ?

Can work either way, i'm inclined to leave as is - but happy to move with the group.

**Comment by guyirvine** [comment]
Made it work the same as like. 

If you create a card, you can go back in and edit the Question & Why during the same session. After that, plus any one else looking at the card, can only edit the "Looking in to it" & "What we did" sections, or add comments.

**Comment by kirstylaurence** [comment]
Brilliant!

Sent from my iPhone

Kirsty Laurence
Project Analyst

[cid:logolic_gif_308D3DB4-C4BF-D542-5770-F48D7156E725]

Private Bag 3016 (Cnr Ruakura & Morrinsville Roads, Newstead)
Hamilton 3240 NEW ZEALAND

Mobile: 027 427 9722
Web: www.lic.co.nz

---

This message is for the named person's use only. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mis-transmission. If you receive this message in error, please immediately delete it and all copies of it from your system, destroy any hard copies of it and notify the sender. LIC reserves the right to monitor all e-mail communications through its networks. Although LIC regularly scans its computer systems for viruses using anti-virus software, LIC is not responsible for the consequences of any viruses, data corruption, interception or unauthorised amendment to this email. The recipient should check this email and any attachments for viruses and defects. This email does not designate an information system for the purposes of section 11(a) of the NZ Electronic Transactions Act 2002.

On 15/07/2016, at 7:11 AM, Guy Irvine <notifications@github.com<mailto:notifications@github.com>> wrote:

Made it work the same as like.

If you create a card, you can go back in and edit the Question & Why during the same session. After that, plus any one else looking at the card, can only edit the "Looking in to it" & "What we did" sections, or add comments.
