### ISSUE TITLE
Some of the pop up's have 'Close' and the 'x'

### ISSUE THREAD

**Issue by kirstylaurence** [guyirvine/haveyoursay#43]
Should they only have one?! :)

**Comment by guyirvine** [comment]
Apparently, all good from the UX dude :)

**Comment by kirstylaurence** [comment]
Hahah really?!
☺

Kirsty Laurence
Project Analyst

[cid:logolic_gif_308D3DB4-C4BF-D542-5770-F48D7156E725]

Private Bag 3016 (Cnr Ruakura & Morrinsville Roads, Newstead)
Hamilton 3240 NEW ZEALAND

Mobile: 027 427 9722
Web: www.lic.co.nz

---

This message is for the named person's use only. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mis-transmission. If you receive this message in error, please immediately delete it and all copies of it from your system, destroy any hard copies of it and notify the sender. LIC reserves the right to monitor all e-mail communications through its networks. Although LIC regularly scans its computer systems for viruses using anti-virus software, LIC is not responsible for the consequences of any viruses, data corruption, interception or unauthorised amendment to this email. The recipient should check this email and any attachments for viruses and defects. This email does not designate an information system for the purposes of section 11(a) of the NZ Electronic Transactions Act 2002.
